Importing the Dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [5]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
27814,34711,1.443955,-1.052462,-0.141721,-1.564017,-0.966274,-0.333886,-0.777060,0.023616,-2.168826,...,-0.479940,-1.165220,0.155226,-0.409701,0.179672,-0.446258,0.004329,0.000060,32.39,0.0
27815,34711,-0.263364,0.931818,1.193111,-0.507924,0.862019,0.249381,0.815449,-0.090801,-0.520583,...,-0.310112,-0.648621,-0.253746,-1.030111,-0.046091,0.107328,0.101296,-0.124600,1.49,0.0
27816,34712,0.976345,-1.024867,0.978714,0.639442,-1.413711,0.311635,-0.909035,0.232423,-0.493025,...,-0.279978,-0.599463,-0.081403,-0.059427,0.202311,-0.405753,0.055109,0.052975,151.00,0.0
27817,34712,1.464604,-0.437919,-0.018869,-1.057177,-0.154243,0.251215,-0.584866,-0.025483,-0.841369,...,-0.148384,-0.454571,-0.019732,-1.313689,0.379650,-0.368497,0.031746,0.007238,8.00,0.0
27818,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27819 entries, 0 to 27818
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    27819 non-null  int64
 1   V1      27818 non-null  float64
 2   V2      27818 non-null  float64
 3   V3      27818 non-null  float64
 4   V4      27818 non-null  float64
 5   V5      27818 non-null  float64
 6   V6      27818 non-null  float64
 7   V7      27818 non-null  float64
 8   V8      27818 non-null  float64
 9   V9      27818 non-null  float64
 10  V10     27818 non-null  float64
 11  V11     27818 non-null  float64
 12  V12     27818 non-null  float64
 13  V13     27818 non-null  float64
 14  V14     27818 non-null  float64
 15  V15     27818 non-null  float64
 16  V16     27818 non-null  float64
 17  V17     27818 non-null  float64
 18  V18     27818 non-null  float64
 19  V19     27818 non-null  float64
 20  V20     27818 non-null  float64
 21  V21     27818 non-null  float64
 22  V22     27818 non-null  float64
 23  V23     27818 non-null  float64
 24  V24     27818 non-null  float64
 25  V25     27818 non-null  float64
 26  V26     27818 non-null  float64
 27  V27     27818 non-null  float64
 28  V28     27818 non-null  float64
 29  Amount  27818 non-null  float64
 30  Class   27818 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.6 MB

In [8]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        1
V2        1
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    27725
1.0       93
Name: count, dtype: int64

In [10]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
# statistical measures of the data
legit.Amount.describe()

count    27725.000000
mean        77.232517
std        219.509762
min          0.000000
25%          6.490000
50%         19.950000
75%         69.320000
max       7879.420000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count      93.000000
mean       96.609677
std       259.128010
min         0.000000
25%         1.000000
50%         1.100000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [13]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,20440.754518,-0.190595,0.129284,0.765200,0.201632,-0.180681,0.092904,-0.099318,0.014884,0.405538,...,0.041673,-0.037007,-0.125822,-0.040202,0.011510,0.129192,0.022983,0.010650,0.003732,77.232517
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [14]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11972,20674,1.253266,-0.377012,0.862364,-0.584105,-1.090448,-0.600345,-0.749246,-0.017698,3.332000,...,-0.195256,-0.153254,-0.061842,-0.047827,0.475835,-0.699573,0.055660,0.024258,11.85,0.0
19766,30545,-1.380567,1.201471,-0.261580,-2.417684,2.947438,2.954588,0.701398,0.771655,-0.342518,...,-0.115841,-0.521262,-0.429460,1.006819,0.954325,0.136534,0.016596,0.152840,3.91,0.0
27696,34663,-0.362342,1.107604,1.187032,-0.136280,0.300032,-0.458288,0.634919,0.065335,-0.712062,...,-0.227723,-0.594800,-0.074764,-0.039022,-0.128159,0.073333,0.244821,0.085928,2.99,0.0
8768,11946,1.226882,-0.097081,0.652880,0.408808,-0.698578,-0.700242,-0.249452,-0.230592,2.028404,...,-0.251306,-0.261363,-0.066802,0.445704,0.421075,1.069890,-0.095849,-0.002511,25.60,0.0
9071,12703,1.378279,-0.337794,0.332075,-0.522067,-0.894863,-1.096964,-0.455523,-0.180697,0.196260,...,-0.312579,-0.906909,0.178081,0.395986,0.205871,-0.595435,-0.056889,-0.004162,9.95,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
26802,34256,0.539276,1.554890,-2.066180,3.241617,0.184736,0.028330,-1.515521,0.537035,-1.999846,...,0.371773,0.111955,-0.305225,-1.053835,0.771175,0.240878,0.418435,0.232170,19.02,1.0
27362,34521,1.081234,0.416414,0.862919,2.520863,-0.005021,0.563341,-0.123372,0.223122,-0.673598,...,-0.159387,-0.305154,0.053620,0.011761,0.375146,-0.106299,0.021008,0.010559,1.52,1.0
27627,34634,0.333499,1.699873,-2.596561,3.643945,-0.585068,-0.654659,-2.275789,0.675229,-2.042416,...,0.469212,-0.144363,-0.317981,-0.769644,0.807855,0.228164,0.551002,0.305473,18.96,1.0
27738,34684,-2.439237,2.591458,-2.840126,1.286244,-1.777016,-1.436139,-2.206056,-2.282725,-0.292885,...,1.774460,-0.771390,0.065727,0.103916,-0.057578,0.242652,-0.268649,-0.743713,125.30,1.0
27749,34687,-0.860827,3.131790,-5.052968,5.420941,-2.494141,-1.811287,-5.479117,1.189472,-3.908206,...,1.192694,0.090356,-0.341881,-0.215924,1.053032,0.271139,1.373300,0.691195,19.02,1.0

In [18]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     93
Name: count, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,20349.463415,-0.084398,0.075202,0.811638,0.157106,-0.161594,0.135007,-0.069850,0.009254,0.430065,...,0.050874,-0.042041,-0.156028,-0.031813,0.031306,0.169231,0.030406,0.008220,0.009711,78.497744
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

Splitting the data into Features & Targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
11972  20674  1.253266 -0.377012  0.862364 -0.584105 -1.090448 -0.600345
19766  30545 -1.380567  1.201471 -0.261580 -2.417684  2.947438  2.954588
27696  34663 -0.362342  1.107604  1.187032 -0.136280  0.300032 -0.458288
8768   11946  1.226882 -0.097081  0.652880  0.408808 -0.698578 -0.700242
9071   12703  1.378279 -0.337794  0.332075 -0.522067 -0.894863 -1.096964
...      ...       ...       ...       ...       ...       ...       ...
26802  34256  0.539276  1.554890 -2.066180  3.241617  0.184736  0.028330
27362  34521  1.081234  0.416414  0.862919  2.520863 -0.005021  0.563341
27627  34634  0.333499  1.699873 -2.596561  3.643945 -0.585068 -0.654659
27738  34684 -2.439237  2.591458 -2.840126  1.286244 -1.777016 -1.436139
27749  34687 -0.860827  3.131790 -5.052968  5.420941 -2.494141 -1.811287

             V7        V8        V9  ...       V20       V21       V22  \
11972 -0.749246 -0.017698  3.332000  ... -0.220882 -0.195256 -0.153254
19766  0.701398  0.771655 -0.342518  ...  0.110954 -0.115841 -0.521262
27696  0.634919  0.065335 -0.712062  ...  0.170146 -0.227723 -0.594800
8768  -0.249452 -0.230592  2.028404  ... -0.076856 -0.251306 -0.261363
9071  -0.455523 -0.180697  0.196260  ... -0.088190 -0.312579 -0.906909
...         ...       ...       ...  ...       ...       ...       ...
26802 -1.515521  0.537035 -1.999846  ...  0.302735  0.371773  0.111955
27362 -0.123372  0.223122 -0.673598  ... -0.165249 -0.159387 -0.305154
27627 -2.275789  0.675229 -2.042416  ...  0.329342  0.469212 -0.144363
27738 -2.206056 -2.282725 -0.292885  ...  0.513530  1.774460 -0.771390
27749 -5.479117  1.189472 -3.908206  ...  1.085760  1.192694  0.090356

            V23       V24       V25       V26       V27       V28  Amount
11972 -0.061842 -0.047827  0.475835 -0.699573  0.055660  0.024258   11.85
19766 -0.429460  1.006819  0.954325  0.136534  0.016596  0.152840    3.91
27696 -0.074764 -0.039022 -0.128159  0.073333  0.244821  0.085928    2.99
8768  -0.066802  0.445704  0.421075  1.069890 -0.095849 -0.002511   25.60
9071   0.178081  0.395986  0.205871 -0.595435 -0.056889 -0.004162    9.95
...         ...       ...       ...       ...       ...       ...     ...
26802 -0.305225 -1.053835  0.771175  0.240878  0.418435  0.232170   19.02
27362  0.053620  0.011761  0.375146 -0.106299  0.021008  0.010559    1.52
27627 -0.317981 -0.769644  0.807855  0.228164  0.551002  0.305473   18.96
27738  0.065727  0.103916 -0.057578  0.242652 -0.268649 -0.743713  125.30
27749 -0.341881 -0.215924  1.053032  0.271139  1.373300  0.691195   19.02

[585 rows x 30 columns]

In [22]:
print(Y)

11972    0.0
19766    0.0
27696    0.0
8768     0.0
9071     0.0
        ...
26802    1.0
27362    1.0
27627    1.0
27738    1.0
27749    1.0
Name: Class, Length: 585, dtype: float64

Split the data into Training data & Testing Data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(585, 30) (468, 30) (117, 30)

Model Training

Logistic Regression

In [25]:
model = LogisticRegression()

In [37]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Acuuracy score

In [27]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [28]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9786324786324786

In [29]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [30]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9829059829059829

RandomForest

In [31]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
model1.fit(X_train, Y_train)

RandomForestClassifier()

In [32]:
# accuracy on training data
X_train_prediction = model1.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [33]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9829059829059829

In [34]:
# accuracy on test data
X_test_prediction = model1.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [35]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9914529914529915

The RandomForest algorithm gives a better score

In [42]:
import joblib

# Save the trained model to a file
joblib.dump(model1, 'fraud_detection_model.pkl')
print("Model saved successfully!")

Model saved successfully!

In [39]:
import joblib
import numpy as np

# Load the saved model (and scaler if applicable)
loaded_model = joblib.load('fraud_detection_model.pkl')
# loaded_scaler = joblib.load('scaler.pkl')

In [48]:
import joblib
# Save the trained model to a file
joblib.dump(model, 'fraud_detection_model_lr.pkl')
print("Model saved successfully!")

Model saved successfully!